### ISSUE TITLE
 is this worth a PR? Killable wrapper helper with sync.WaitGroup

### ISSUE THREAD

**Issue by mikeatlas** [icholy/killable#4]
Thanks for the great library - I found that I was creating `Killable`s in the same exact manner, and in using `sync.WaitGroup` in conjunction with graceful kill-all `Killable`s, I could use a build/helper. Would this be worth a PR?

``` go
func CreateKillable(fn func(), wg sync.WaitGroup) (killable.Killable, sync.WaitGroup) {
    theKillable := killable.New()
    go func() {
        <-theKillable.Dying()
        fmt.Println("Dying")

        <-theKillable.Dead()
        fmt.Println("Dead")
    }()
    wg.Add(1)
    killable.Go(theKillable, func() error {
        fn()
        defer wg.Done()
        return nil
    })

    return theKillable, wg
}
```

I call this method several times, for example, my main application has something like:

``` go
func RunServer() {
    var wg sync.WaitGroup

    killableServiceABC, wg =
        CreateKillable(abc.ABCServiceStart, wg)

    killableServiceDEF, wg =
        CreateKillable(def.DEFServiceStart, wg)

    wg.Wait()
}

func KillServer() {
    if killableServiceABC != nil {
        killableServiceABC.Kill(fmt.Errorf(
            "Shutting down ABC Server..."))
        abc.StopABC()
    }
    if killableServiceDEF != nil {
        killableServiceDEF.Kill(fmt.Errorf(
            "Shutting down DEF Server..."))
        def.StopDEF()
    }
}
```

**Comment by icholy** [comment]
Hmm, I notice a few things off the bat. 
1. Don't need to defer in `defer wg.Done()` it's the last thing before the return.
2. The invocation of `killable.Go` in `CreateKillable` doesn't actually use any of `killable`s functionality. You might as well just use a regular `go` there.
3. You seem to be storing the `Killable` instances in global variables. They should be tied to the context they're controlling.

Here's a better way to architect a service.

``` go
type ServiceA struct {
    // embed the killable so `ServiceA` **becomes** a Killable.
    killable.Killable
}

func (s *ServiceA) startup() error {
    // do async stuff
    return nil
}

func (s *ServiceA) shutdown() {
    // clean up code
}

func NewServiceA() *ServiceA {

    // create the service context
    s := &ServiceA{
        Killable: killable.New(),
    }

    // start the service
    killable.Go(s, s.startup)

    // register a defer to cleanup the service
    killable.Defer(s, s.shutdown)

    return s
}
```

``` go
func RunServer() {

    // a and b are both Killables
    a := NewServiceA()
    b := NewServiceA()

    // wait for them to be dead
    var wg sync.WaitGroup
    wg.Add(2)
    killable.Defer(a, wg.Done)
    killable.Defer(b, wg.Done)
    wg.Wait()

    // or create a parent as use hat
    var p := killable.New(a, b)
    killable.Defer(p, func() {
        // both services are dead
    })
    <-p.Dead()

}
```

**Comment by mikeatlas** [comment]
Appreciated - thanks for the suggestions. Hope this inspires new features for Killable.

**Comment by icholy** [comment]
Sorry if I didn't help. I don't think I have information to understand what you're trying to achieve. Either way, I appreciate the input. I think I might need to improve the README a bit.

**Comment by mikeatlas** [comment]
Helpful! I was just trying to reduce repeat boilerplate with a pattern on top of Killable.

**Comment by icholy** [comment]
Yeah, that pattern seems to be pretty specific to your setup.  I have a bunch of killable helpers in my code that I don't add to the package. I want to keep it lean.
